apiVersion: apps/v1
kind: Deployment
metadata:
  name: nave-flask
  labels:
    app: nave-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nave-flask
  template:
    metadata:
      labels:
        app: nave-flask
    spec:
      containers:
      - name: nave-flask
        image: REPLACE_IMAGE
        ports:
        - containerPort: 5000
