apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: nave-flask
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
      nodePort: 30001
      name: http