pipeline {
  agent any
  environment {
    COMMIT = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
    DOCKER_REPOSITORY = ""
    BRANCH = "main"
    TAG = ""
  }
  stages {
    stage('Git pull') {
      steps {
        sh "git pull origin $BRANCH"
      }
    }
    stage('build & push & run') {
      steps {
        sh "cd flask"
        sh "ls"
      }
    }
  }
  post {  
    failure {  
      sh "echo Sending Failed Email!"
        emailext body: '${DEFAULT_CONTENT} - CI/CD Pipeline has been failed!',
        subject: '${DEFAULT_SUBJECT} - CI/CD pipeline failed!',
        mimeType: 'text/html',to: ''
    } 
  }
}
